utils_dns.c: fix build on OSX
utils_dns.c:759:11: error: use of undeclared identifier 'ns_t_apl'
            case ns_t_apl:      return ("APL");

Apparently Apple forgot to add some record types
when they bumped the version number of /usr/include/arpa/nameser.h