Added missing include of 'config.h'
This adressed to solve compilation issue on Solaris platform:

In file included from src/libcollectdclient/network_parse.c:26:0,
                 from src/libcollectdclient/network_parse_test.c:32:
                 ./src/config.h:1517:0: error: "_FILE_OFFSET_BITS" redefined