Added missing include of 'kstat.h'
This adressed to solve compilation issue on Solaris platform:

src/utils_vl_lookup.c:37:1: error: unknown type name 'kstat_ctl_t'
 kstat_ctl_t *kc;