Added missing include of 'kstat.h'
This adressed to solve compilation issue on Solaris platform:

src/daemon/common.c:64:8: error: unknown type name 'kstat_ctl_t'
  extern kstat_ctl_t *kc;