Fix 'make distcheck' (for `master-aggregation` hook)
Change introduced in df135922b19890047ebf725e6b82cd1c174c6d52 (#2810)

This change causes error in 'master-aggregation' hook:

ERROR: files left in build directory after distclean:
./liboconfig.la
./libcommon.la
./libmount.la
./libformat_json.la
./libheap.la
./libignorelist.la
./libavltree.la
./libformat_graphite.la
./liblatency.la
./liblookup.la
./libmetadata.la
./libcmds.la