gcc compat: Use alloca explicitly instead of VLA
When -Wall is used, compilation issues of the below kind are fixed:

src/libcollectdclient/network_buffer.c:273:11: error: unbounded use of
variable-length array [-Werror=vla-larger-than=]
  273 |   uint8_t pkg_values_types[vl->values_len];
      |           ^~~~~~~~~~~~~~~~
src/libcollectdclient/network_buffer.c:274:11: error: argument to
variable-length array may be too large [-Werror=vla-larger-than=]
  274 |   value_t pkg_values[vl->values_len];
      |           ^~~~~~~~~~
src/libcollectdclient/network_buffer.c: In function
‘lcc_network_buffer_add_value’:
src/libcollectdclient/network_buffer.c:274:11: note: limit is 16 bytes,
but argument may be as large as 18446744073709551615

Signed-off-by: Anatol Belski <anbelski@linux.microsoft.com>