fix: Rely on memcpy instead of strncpy
* Circumvent

```
In function 'ls_parse',
    inlined from 'ls_read_parse' at src/livestatus.c:303:10,
    inlined from 'ls_read' at src/livestatus.c:450:8:
src/livestatus.c:250:5: error: 'strncpy' destination unchanged after copying no bytes [-Werror=stringop-truncation]
  250 |     strncpy(fields[i], wstart, pchar - wstart);
```