disk plugin: fix build on Solaris
  CC       disk_la-disk.lo
disk.c:296:13: error: ‘submit_io_time’ defined but not used
[-Werror=unused-function]
 static void submit_io_time (char const *plugin_instance, derive_t
io_time, derive_t weighted_time)
             ^
cc1: all warnings being treated as errors

Thanks @dago for letting me know.