python plugin: fix building with python 3
Python 3 doesn't have PyUnicode_SetDefaultEncoding()

CC       python_la-python.lo
python.c: In function 'cpy_config':
python.c:1138:4: error: implicit declaration of function 'PyUnicode_SetDefaultEncoding' [-Werror=implicit-function-declaration]
    if (PyUnicode_SetDefaultEncoding(encoding)) {
    ^
cc1: all warnings being treated as errors
*** Error code 1