collectd-tg: Remove use of NAN.
This broke the build under Solaris, once again *sigh*.

collectd-tg.c: In function ‘dtime’:
collectd-tg.c:108:12: error: ‘NAN’ undeclared (first use in this function)
     return NAN;
            ^