Fix new qpos library call missing an arguement
Fixes compile error:
src/intel_rdt.c: In function ‘rdt_init_cores_monitoring’:
src/intel_rdt.c:1406:48: error: passing argument 5 of \
‘pqos_mon_start_cores’ from incompatible pointer type \
[-Wincompatible-pointer-types]

Cmp with latest /usr/include/pqos.h lines 1044-1105.
The new pqos_mon_start_cores has a new arguement at position 5
and now takes 6 arguements:
https://github.com/intel/intel-cmt-cat/commit/6496fa8c2bd935745dfceb3cc6d17688b309a38e

int pqos_mon_start_cores(const unsigned num_cores,
                         const unsigned *cores,
                         const enum pqos_mon_event event,
                         void *context,
----->
                         struct pqos_mon_mem_region *mem_region,
----->
                         struct pqos_mon_data **group);