Added missing include of 'kstat.h' and variable declaration
This adressed to solve compilation issue on Solaris platform:

src/daemon/collectd.c:212: error: 'kc' undeclared (first use in this function)
src/daemon/collectd.c:213: error: implicit declaration of function 'kstat_open'