src/gpu_nvidia.c: Fix a compiler error since cuda-nvml-devel-13
nvmlDeviceGetTemperature() has been deprecated since cuda-nvml-devel-13.
so try to fix the compiler error by adding nvmlDeviceGetTemperatureV().
------------------------------------------------------------------------
src/gpu_nvidia.c: In function 'nvml_read':
src/gpu_nvidia.c:197:5: error: 'nvmlDeviceGetTemperature' is deprecated [-Werror=deprecated-declarations]
  197 |     TRYOPT(nvmlDeviceGetTemperature(dev, NVML_TEMPERATURE_GPU, &core_temp))
      |     ^~~~~~
In file included from src/gpu_nvidia.c:27:
/usr/local/cuda-13.1/include/nvml.h:5706:39: note: declared here
 5706 | DEPRECATED(13.0) nvmlReturn_t DECLDIR nvmlDeviceGetTemperature(nvmlDevice_t device, nvmlTemperatureSensors_t sensorType, unsigned int *temp);
      |
------------------------------------------------------------------------

Signed-off-by: Xiao Yang <xyang@ddn.com>